---
nfs_mount_point: /mnt/shared

nfs_mount_option:
  - default #the normal rw,suid,dev,auto
  - _netdev #marks this as network-dependent so systemd orders it after the network is up

nfs_app_user: ansible