---
- name: config NFS server
  hosts: nfs_servers
  become: true
  roles:
    - role : nfs_common
      tags : [common]
    - role : nfs_servers
      tags : [server]

- name: configure the NFS client
  hosts: nfs_clients
  become: true
  roles:
    - role: nfs_common
      tags: [common]
    - role: nfs_clients
      tags: [client]