---
all:
  childern:
    nfs_servers:
      hosts:
        nfs-server-01:
          ansible-hosts: 192.168.0.2
        
    nfs_clients:
      hosts:
        nfs-client-01:
          ansible-hosts: 192.168.0.21
        nfs-client-02:
          ansible-hosts: 192.168.0.22
        nfs-client-03:
          ansible-hosts: 192.168.0.23
        nfs-client-04:
          ansible-hosts: 192.168.0.24
        nfs-client-05:
          ansible-hosts: 192.168.0.25